export const SBK_SHEETNAMES = [
  'SBK_Campaigns',
  'SBK_Creatives',
  'SBK_LandingPages',
  'SBK_Keywords',
  'SBK_NegativeKeywords',
];

export const SBE_SHEETNAMES = [
  'SBE_Campaigns',
  'SBE_Creatives',
  'SBE_LandingPages',
  'SBE_Targets',
  'SBE_Expressions',
  'SBE_NegativeTargets',
];

export const SBK_WORKBOOK = [
  [
    {
      Name: 'Campaign1',
      Budget: '1111',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'enabled',
      BrandEntityId: 'id1',
      BidOptimization: 'true',
      BidMultiplier: '45',
      PortfolioId: '23432',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      Name: 'Campaign2',
      Budget: '2222',
      BudgetType: 'daily',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'archived',
      BrandEntityId: 'id2',
      BidOptimization: 'true',
      BidMultiplier: '46',
      PortfolioId: '4243',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      Name: 'Campaign3',
      Budget: '3333',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'archived',
      BrandEntityId: 'id3',
      BidOptimization: 'false',
      BidMultiplier: '47',
      PortfolioId: '2345',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      Name: 'Campaign4',
      Budget: '4444',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'video',
      State: 'paused',
      BrandEntityId: 'id4',
      BidOptimization: 'true',
      BidMultiplier: '67',
      PortfolioId: '564',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      Name: 'Campaign5',
      Budget: '5555',
      BudgetType: 'daily',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'video',
      State: 'enabled',
      BrandEntityId: 'id5',
      BidOptimization: 'false',
      BidMultiplier: '88',
      PortfolioId: '6878',
      rowIndex: 4,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      BrandName: 'CreativeBrandName1',
      BrandLogoAssetID: 'BrandLogoAssetId1',
      Headline: 'headline1',
      Asins: 'creativeasin1, creativeasin2, creativeasin3',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      BrandName: 'CreativeBrandName2',
      BrandLogoAssetID: 'BrandLogoAssetId2',
      Headline: 'headline2',
      Asins: 'creativeasin5, creativeasin6, creativeasin7',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      BrandName: 'CreativeBrandName3',
      BrandLogoAssetID: 'BrandLogoAssetId3',
      Headline: 'headline3',
      Asins: 'creativeasin8, creativeasin9, creativeasin10',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      BrandName: 'CreativeBrandName4',
      BrandLogoAssetID: 'BrandLogoAssetId4',
      Headline: 'headline4',
      Asins: 'creativeasin11, creativeasin12, creativeasin13',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      BrandName: 'CreativeBrandName5',
      BrandLogoAssetID: 'BrandLogoAssetId5',
      Headline: 'headline5',
      Asins: 'creativeasin14, creativeasin15, creativeasin16',
      rowIndex: 4,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      Asins: 'landingpageasin1, landingpageasin2, landingpage3',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Asins: 'landingpageasin1, landingpageasin2, landingpage4',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Asins: 'landingpageasin1, landingpageasin2, landingpage5',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Asins: 'landingpageasin1, landingpageasin2, landingpage6',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Asins: 'landingpageasin1, landingpageasin2, landingpage7',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 4,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText1',
      NativeLanguageKeyword: 'language1',
      NativeLanguageLocale: 'Local1',
      MatchType: 'broad',
      Bid: '234',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText2',
      NativeLanguageKeyword: 'language2',
      NativeLanguageLocale: 'Local2',
      MatchType: 'phrase',
      Bid: '235',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText3',
      NativeLanguageKeyword: 'language3',
      NativeLanguageLocale: 'Local3',
      MatchType: 'broad',
      Bid: '236',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText4',
      NativeLanguageKeyword: 'language4',
      NativeLanguageLocale: 'Local4',
      MatchType: 'exact',
      Bid: '237',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText5',
      NativeLanguageKeyword: 'language5',
      NativeLanguageLocale: 'Local5',
      MatchType: 'broad',
      Bid: '238',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText6',
      NativeLanguageKeyword: 'language6',
      NativeLanguageLocale: 'Local6',
      MatchType: 'broad',
      Bid: '239',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText7',
      NativeLanguageKeyword: 'language7',
      NativeLanguageLocale: 'Local7',
      MatchType: 'phrase',
      Bid: '240',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText8',
      NativeLanguageKeyword: 'language8',
      NativeLanguageLocale: 'Local8',
      MatchType: 'exact',
      Bid: '241',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText9',
      NativeLanguageKeyword: 'language9',
      NativeLanguageLocale: 'Local9',
      MatchType: 'broad',
      Bid: '242',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      KeywordText: 'KeywordText10',
      NativeLanguageKeyword: 'language10',
      NativeLanguageLocale: 'Local10',
      MatchType: 'exact',
      Bid: '243',
      rowIndex: 9,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      KeywordText: 'KeywordText11',
      NativeLanguageKeyword: 'language11',
      NativeLanguageLocale: 'Local11',
      MatchType: 'phrase',
      Bid: '244',
      rowIndex: 10,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText1',
      MatchType: 'negativeExact',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText2',
      MatchType: 'negativePhrase',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText3',
      MatchType: 'negativeExact',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText4',
      MatchType: 'negativeExact',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText5',
      MatchType: 'negativePhrase',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText6',
      MatchType: 'negativeExact',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText7',
      MatchType: 'negativePhrase',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText8',
      MatchType: 'negativePhrase',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText9',
      MatchType: 'negativeExact',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      KeywordText: 'KeywordText10',
      MatchType: 'negativeExact',
      rowIndex: 9,
      errorCount: 0,
    },
  ],
];

export const SBE_WORKBOOK = [
  [
    {
      Name: 'Campaign1',
      Budget: '1111',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'enabled',
      BrandEntityId: 'id1',
      BidOptimization: 'true',
      BidMultiplier: '45',
      PortfolioId: '23432',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      Name: 'Campaign2',
      Budget: '2222',
      BudgetType: 'daily',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'archived',
      BrandEntityId: 'id2',
      BidOptimization: 'true',
      BidMultiplier: '46',
      PortfolioId: '4243',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      Name: 'Campaign3',
      Budget: '3333',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'archived',
      BrandEntityId: 'id3',
      BidOptimization: 'false',
      BidMultiplier: '47',
      PortfolioId: '2345',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      Name: 'Campaign4',
      Budget: '4444',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'video',
      State: 'paused',
      BrandEntityId: 'id4',
      BidOptimization: 'true',
      BidMultiplier: '67',
      PortfolioId: '564',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      Name: 'Campaign5',
      Budget: '5555',
      BudgetType: 'daily',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'video',
      State: 'enabled',
      BrandEntityId: 'id5',
      BidOptimization: 'false',
      BidMultiplier: '88',
      PortfolioId: '6878',
      rowIndex: 4,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      BrandName: 'CreativeBrandName1',
      BrandLogoAssetId: 'BrandLogoAssetId1',
      Headline: 'headline1',
      Asins: 'creativeasin1, creativeasin2, creativeasin3',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      BrandName: 'CreativeBrandName2',
      BrandLogoAssetId: 'BrandLogoAssetId2',
      Headline: 'headline2',
      Asins: 'creativeasin5, creativeasin6, creativeasin7',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      BrandName: 'CreativeBrandName3',
      BrandLogoAssetId: 'BrandLogoAssetId3',
      Headline: 'headline3',
      Asins: 'creativeasin8, creativeasin9, creativeasin10',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      BrandName: 'CreativeBrandName4',
      BrandLogoAssetId: 'BrandLogoAssetId4',
      Headline: 'headline4',
      Asins: 'creativeasin11, creativeasin12, creativeasin13',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      BrandName: 'CreativeBrandName5',
      BrandLogoAssetId: 'BrandLogoAssetId5',
      Headline: 'headline5',
      Asins: 'creativeasin14, creativeasin15, creativeasin16',
      rowIndex: 4,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      Asins: 'landingpageasin1, landingpageasin2, landingpage3',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Asins: 'landingpageasin1, landingpageasin2, landingpage4',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Asins: 'landingpageasin1, landingpageasin2, landingpage5',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Asins: 'landingpageasin1, landingpageasin2, landingpage6',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Asins: 'landingpageasin1, landingpageasin2, landingpage7',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 4,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      Name: 'Target1',
      Bid: '123',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      Name: 'Target2',
      Bid: '124',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Name: 'Target3',
      Bid: '125',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Name: 'Target4',
      Bid: '126',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'Target5',
      Bid: '127',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'Target6',
      Bid: '128',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'Target7',
      Bid: '129',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Name: 'Target8',
      Bid: '130',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Name: 'Target9',
      Bid: '131',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Name: 'Target10',
      Bid: '132',
      rowIndex: 9,
      errorCount: 0,
    },
  ],
  [
    {
      TargetName: 'Target1',
      Type: 'asinReviewRatingLessThan',
      Value: '2-5',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      TargetName: 'Target1',
      Type: 'asinCategorySameAs',
      Value: '2-6',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      TargetName: 'Target1',
      Type: 'asinCategorySameAs',
      Value: '2-7',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      TargetName: 'Target1',
      Type: 'asinReviewRatingLessThan',
      Value: '2-8',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      TargetName: 'Target1',
      Type: 'asinPriceLessThan',
      Value: '2-9',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      TargetName: 'Target2',
      Type: 'asinCategorySameAs',
      Value: '2-10',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      TargetName: 'Target2',
      Type: 'asinReviewRatingGreaterThan',
      Value: '2-11',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinCategorySameAs',
      Value: '2-12',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinCategorySameAs',
      Value: '2-13',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinCategorySameAs',
      Value: '2-14',
      rowIndex: 9,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinReviewRatingLessThan',
      Value: '2-15',
      rowIndex: 10,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinCategorySameAs',
      Value: '2-16',
      rowIndex: 11,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinPriceLessThan',
      Value: '2-17',
      rowIndex: 12,
      errorCount: 0,
    },
    {
      TargetName: 'Target4',
      Type: 'asinReviewRatingGreaterThan',
      Value: '2-18',
      rowIndex: 13,
      errorCount: 0,
    },
    {
      TargetName: 'Target5',
      Type: 'asinCategorySameAs',
      Value: '2-19',
      rowIndex: 14,
      errorCount: 0,
    },
    {
      TargetName: 'Target5',
      Type: 'asinCategorySameAs',
      Value: '2-20',
      rowIndex: 15,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinPriceLessThan',
      Value: '2-21',
      rowIndex: 16,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinReviewRatingLessThan',
      Value: '2-22',
      rowIndex: 17,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinCategorySameAs',
      Value: '2-23',
      rowIndex: 18,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinCategorySameAs',
      Value: '2-24',
      rowIndex: 19,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinPriceLessThan',
      Value: '2-25',
      rowIndex: 20,
      errorCount: 0,
    },
    {
      TargetName: 'Target7',
      Type: 'asinCategorySameAs',
      Value: '2-26',
      rowIndex: 21,
      errorCount: 0,
    },
    {
      TargetName: 'Target8',
      Type: 'asinCategorySameAs',
      Value: '2-27',
      rowIndex: 22,
      errorCount: 0,
    },
    {
      TargetName: 'Target8',
      Type: 'asinReviewRatingLessThan',
      Value: '2-28',
      rowIndex: 23,
      errorCount: 0,
    },
    {
      TargetName: 'Target9',
      Type: 'asinPriceLessThan',
      Value: '2-29',
      rowIndex: 24,
      errorCount: 0,
    },
    {
      TargetName: 'Target9',
      Type: 'asinCategorySameAs',
      Value: '2-30',
      rowIndex: 25,
      errorCount: 0,
    },
    {
      TargetName: 'Target9',
      Type: 'asinCategorySameAs',
      Value: '2-31',
      rowIndex: 26,
      errorCount: 0,
    },
    {
      TargetName: 'Target10',
      Type: 'asinCategorySameAs',
      Value: '2-32',
      rowIndex: 27,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      Type: 'asinReviewRatingLessThan',
      Value: '2-5',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Type: 'asinCategorySameAs',
      Value: '2-6',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Type: 'asinCategorySameAs',
      Value: '2-7',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Type: 'asinReviewRatingLessThan',
      Value: '2-8',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Type: 'asinPriceLessThan',
      Value: '2-9',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Type: 'asinCategorySameAs',
      Value: '2-10',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Type: 'asinReviewRatingGreaterThan',
      Value: '2-11',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Type: 'asinCategorySameAs',
      Value: '2-12',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Type: 'asinCategorySameAs',
      Value: '2-13',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Type: 'asinCategorySameAs',
      Value: '2-14',
      rowIndex: 9,
      errorCount: 0,
    },
  ],
];
