export const SBK_SHEETNAMES = [
  'SBK_Campaigns',
  'SBK_Creatives',
  'SBK_LandingPages',
  'SBK_Keywords',
  'SBK_NegativeKeywords',
];
export const SBE_SHEETNAMES = [
  'SBE_Campaigns',
  'SBE_Creatives',
  'SBE_LandingPages',
  'SBE_Targets',
  'SBE_Expressions',
  'SBE_NegativeTargets',
  'SBE_NegativeExpressions',
];
export const SBVE_SHEETNAMES = [
  'SBVE_Campaigns',
  'SBVE_Creatives',
  'SBVE_Targets',
  'SBVE_Expressions',
  'SBVE_NegativeTargets',
  'SBVE_NegativeExpressions',
];
export const SBVK_SHEETNAMES = [
  'SBVK_Campaigns',
  'SBVK_Creatives',
  'SBVK_Keywords',
  'SBVK_NegativeKeywords',
];
export const SD_SHEETNAMES = [
  'SD_Campaigns',
  'SD_AdGroups',
  'SD_ProductAds',
  'SD_Targetings',
  'SD_Expressions',
  'SD_ExpressionsNested',
  'SD_NegativeTargetings',
  'SD_NegativeExpressions',
];

export const SBK_WORKBOOK = [
  [
    {
      Name: 'Campaign1',
      Budget: '1111',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'enabled',
      BrandEntityId: 'id1',
      BidOptimization: 'true',
      BidMultiplier: '45',
      PortfolioId: '23432',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      Name: 'Campaign2',
      Budget: '2222',
      BudgetType: 'daily',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'archived',
      BrandEntityId: 'id2',
      BidOptimization: 'true',
      BidMultiplier: '46',
      PortfolioId: '4243',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      Name: 'Campaign3',
      Budget: '3333',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'archived',
      BrandEntityId: 'id3',
      BidOptimization: 'false',
      BidMultiplier: '47',
      PortfolioId: '2345',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      Name: 'Campaign4',
      Budget: '4444',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'video',
      State: 'paused',
      BrandEntityId: 'id4',
      BidOptimization: 'true',
      BidMultiplier: '67',
      PortfolioId: '564',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      Name: 'Campaign5',
      Budget: '5555',
      BudgetType: 'daily',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'video',
      State: 'enabled',
      BrandEntityId: 'id5',
      BidOptimization: 'false',
      BidMultiplier: '88',
      PortfolioId: '6878',
      rowIndex: 4,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      BrandName: 'CreativeBrandName1',
      BrandLogoAssetID: 'BrandLogoAssetId1',
      Headline: 'headline1',
      Asins: 'creativeasin1, creativeasin2, creativeasin3',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      BrandName: 'CreativeBrandName2',
      BrandLogoAssetID: 'BrandLogoAssetId2',
      Headline: 'headline2',
      Asins: 'creativeasin5, creativeasin6, creativeasin7',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      BrandName: 'CreativeBrandName3',
      BrandLogoAssetID: 'BrandLogoAssetId3',
      Headline: 'headline3',
      Asins: 'creativeasin8, creativeasin9, creativeasin10',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      BrandName: 'CreativeBrandName4',
      BrandLogoAssetID: 'BrandLogoAssetId4',
      Headline: 'headline4',
      Asins: 'creativeasin11, creativeasin12, creativeasin13',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      BrandName: 'CreativeBrandName5',
      BrandLogoAssetID: 'BrandLogoAssetId5',
      Headline: 'headline5',
      Asins: 'creativeasin14, creativeasin15, creativeasin16',
      rowIndex: 4,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      Asins: 'landingpageasin1, landingpageasin2, landingpage3',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Asins: 'landingpageasin1, landingpageasin2, landingpage4',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Asins: 'landingpageasin1, landingpageasin2, landingpage5',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Asins: 'landingpageasin1, landingpageasin2, landingpage6',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Asins: 'landingpageasin1, landingpageasin2, landingpage7',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 4,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText1',
      NativeLanguageKeyword: 'language1',
      NativeLanguageLocale: 'Local1',
      MatchType: 'broad',
      Bid: '234',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText2',
      NativeLanguageKeyword: 'language2',
      NativeLanguageLocale: 'Local2',
      MatchType: 'phrase',
      Bid: '235',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText3',
      NativeLanguageKeyword: 'language3',
      NativeLanguageLocale: 'Local3',
      MatchType: 'broad',
      Bid: '236',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText4',
      NativeLanguageKeyword: 'language4',
      NativeLanguageLocale: 'Local4',
      MatchType: 'exact',
      Bid: '237',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText5',
      NativeLanguageKeyword: 'language5',
      NativeLanguageLocale: 'Local5',
      MatchType: 'broad',
      Bid: '238',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText6',
      NativeLanguageKeyword: 'language6',
      NativeLanguageLocale: 'Local6',
      MatchType: 'broad',
      Bid: '239',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText7',
      NativeLanguageKeyword: 'language7',
      NativeLanguageLocale: 'Local7',
      MatchType: 'phrase',
      Bid: '240',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText8',
      NativeLanguageKeyword: 'language8',
      NativeLanguageLocale: 'Local8',
      MatchType: 'exact',
      Bid: '241',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText9',
      NativeLanguageKeyword: 'language9',
      NativeLanguageLocale: 'Local9',
      MatchType: 'broad',
      Bid: '242',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      KeywordText: 'KeywordText10',
      NativeLanguageKeyword: 'language10',
      NativeLanguageLocale: 'Local10',
      MatchType: 'exact',
      Bid: '243',
      rowIndex: 9,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      KeywordText: 'KeywordText11',
      NativeLanguageKeyword: 'language11',
      NativeLanguageLocale: 'Local11',
      MatchType: 'phrase',
      Bid: '244',
      rowIndex: 10,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText1',
      MatchType: 'negativeExact',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText2',
      MatchType: 'negativePhrase',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText3',
      MatchType: 'negativeExact',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText4',
      MatchType: 'negativeExact',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText5',
      MatchType: 'negativePhrase',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText6',
      MatchType: 'negativeExact',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText7',
      MatchType: 'negativePhrase',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText8',
      MatchType: 'negativePhrase',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText9',
      MatchType: 'negativeExact',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      KeywordText: 'KeywordText10',
      MatchType: 'negativeExact',
      rowIndex: 9,
      errorCount: 0,
    },
  ],
];
export const SBVK_WORKBOOK = [
  [
    {
      Name: 'Campaign1',
      Budget: '1111',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'enabled',
      BrandEntityId: 'id1',
      PortfolioId: '23432',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      Name: 'Campaign2',
      Budget: '2222',
      BudgetType: 'daily',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'archived',
      BrandEntityId: 'id2',
      PortfolioId: '4243',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      Name: 'Campaign3',
      Budget: '3333',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'archived',
      BrandEntityId: 'id3',
      PortfolioId: '2345',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      Name: 'Campaign4',
      Budget: '4444',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'video',
      State: 'paused',
      BrandEntityId: 'id4',
      PortfolioId: '564',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      Name: 'Campaign5',
      Budget: '5555',
      BudgetType: 'daily',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'video',
      State: 'enabled',
      BrandEntityId: 'id5',
      PortfolioId: '6878',
      rowIndex: 4,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      Asins: 'creativeasin1, creativeasin2, creativeasin3',
      VideoMediaIds:
        'creativevideomediaids1, creativevideomediaids2, landingpage3',
      Type: 'video',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Asins: 'creativeasin5, creativeasin6, creativeasin7',
      VideoMediaIds:
        'creativevideomediaids1, creativevideomediaids2, landingpage4',
      Type: 'video',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Asins: 'creativeasin8, creativeasin9, creativeasin10',
      VideoMediaIds:
        'creativevideomediaids1, creativevideomediaids2, landingpage5',
      Type: 'video',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Asins: 'creativeasin11, creativeasin12, creativeasin13',
      VideoMediaIds:
        'creativevideomediaids1, creativevideomediaids2, landingpage6',
      Type: 'video',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Asins: 'creativeasin14, creativeasin15, creativeasin16',
      VideoMediaIds:
        'creativevideomediaids1, creativevideomediaids2, landingpage7',
      Type: 'video',
      rowIndex: 4,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText1',
      NativeLanguageKeyword: 'language1',
      NativeLanguageLocale: 'Local1',
      MatchType: 'broad',
      Bid: '234',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText2',
      NativeLanguageKeyword: 'language2',
      NativeLanguageLocale: 'Local2',
      MatchType: 'phrase',
      Bid: '235',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText3',
      NativeLanguageKeyword: 'language3',
      NativeLanguageLocale: 'Local3',
      MatchType: 'broad',
      Bid: '236',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText4',
      NativeLanguageKeyword: 'language4',
      NativeLanguageLocale: 'Local4',
      MatchType: 'exact',
      Bid: '237',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText5',
      NativeLanguageKeyword: 'language5',
      NativeLanguageLocale: 'Local5',
      MatchType: 'broad',
      Bid: '238',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText6',
      NativeLanguageKeyword: 'language6',
      NativeLanguageLocale: 'Local6',
      MatchType: 'broad',
      Bid: '239',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText7',
      NativeLanguageKeyword: 'language7',
      NativeLanguageLocale: 'Local7',
      MatchType: 'phrase',
      Bid: '240',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText8',
      NativeLanguageKeyword: 'language8',
      NativeLanguageLocale: 'Local8',
      MatchType: 'exact',
      Bid: '241',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText9',
      NativeLanguageKeyword: 'language9',
      NativeLanguageLocale: 'Local9',
      MatchType: 'broad',
      Bid: '242',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      KeywordText: 'KeywordText10',
      NativeLanguageKeyword: 'language10',
      NativeLanguageLocale: 'Local10',
      MatchType: 'exact',
      Bid: '243',
      rowIndex: 9,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      KeywordText: 'KeywordText11',
      NativeLanguageKeyword: 'language11',
      NativeLanguageLocale: 'Local11',
      MatchType: 'phrase',
      Bid: '244',
      rowIndex: 10,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      KeywordText: 'KeywordText1',
      MatchType: 'negativeExact',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText2',
      MatchType: 'negativePhrase',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText3',
      MatchType: 'negativeExact',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      KeywordText: 'KeywordText4',
      MatchType: 'negativeExact',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText5',
      MatchType: 'negativePhrase',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      KeywordText: 'KeywordText6',
      MatchType: 'negativeExact',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText7',
      MatchType: 'negativePhrase',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText8',
      MatchType: 'negativePhrase',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      KeywordText: 'KeywordText9',
      MatchType: 'negativeExact',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      KeywordText: 'KeywordText10',
      MatchType: 'negativeExact',
      rowIndex: 9,
      errorCount: 0,
    },
  ],
];
export const SBE_WORKBOOK = [
  [
    {
      Name: 'Campaign1',
      Budget: '1111',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'enabled',
      BrandEntityId: 'id1',
      BidOptimization: 'true',
      BidMultiplier: '45',
      PortfolioId: '23432',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      Name: 'Campaign2',
      Budget: '2222',
      BudgetType: 'daily',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'archived',
      BrandEntityId: 'id2',
      BidOptimization: 'true',
      BidMultiplier: '46',
      PortfolioId: '4243',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      Name: 'Campaign3',
      Budget: '3333',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'productCollection',
      State: 'archived',
      BrandEntityId: 'id3',
      BidOptimization: 'false',
      BidMultiplier: '47',
      PortfolioId: '2345',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      Name: 'Campaign4',
      Budget: '4444',
      BudgetType: 'lifetime',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'video',
      State: 'paused',
      BrandEntityId: 'id4',
      BidOptimization: 'true',
      BidMultiplier: '67',
      PortfolioId: '564',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      Name: 'Campaign5',
      Budget: '5555',
      BudgetType: 'daily',
      StartDate: '2021/08/01',
      EndDate: '2021/08/01',
      AdFormat: 'video',
      State: 'enabled',
      BrandEntityId: 'id5',
      BidOptimization: 'false',
      BidMultiplier: '88',
      PortfolioId: '6878',
      rowIndex: 4,
      errorCount: 0,
    },
  ], // Campaigns
  [
    {
      CampaignName: 'Campaign1',
      BrandName: 'CreativeBrandName1',
      BrandLogoAssetId: 'BrandLogoAssetId1',
      Headline: 'headline1',
      Asins: 'creativeasin1, creativeasin2, creativeasin3',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      BrandName: 'CreativeBrandName2',
      BrandLogoAssetId: 'BrandLogoAssetId2',
      Headline: 'headline2',
      Asins: 'creativeasin5, creativeasin6, creativeasin7',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      BrandName: 'CreativeBrandName3',
      BrandLogoAssetId: 'BrandLogoAssetId3',
      Headline: 'headline3',
      Asins: 'creativeasin8, creativeasin9, creativeasin10',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      BrandName: 'CreativeBrandName4',
      BrandLogoAssetId: 'BrandLogoAssetId4',
      Headline: 'headline4',
      Asins: 'creativeasin11, creativeasin12, creativeasin13',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      BrandName: 'CreativeBrandName5',
      BrandLogoAssetId: 'BrandLogoAssetId5',
      Headline: 'headline5',
      Asins: 'creativeasin14, creativeasin15, creativeasin16',
      rowIndex: 4,
      errorCount: 0,
    },
  ], // Creatives
  [
    {
      CampaignName: 'Campaign1',
      Asins: 'landingpageasin1, landingpageasin2, landingpage3',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Asins: 'landingpageasin1, landingpageasin2, landingpage4',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Asins: 'landingpageasin1, landingpageasin2, landingpage5',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Asins: 'landingpageasin1, landingpageasin2, landingpage6',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Asins: 'landingpageasin1, landingpageasin2, landingpage7',
      Url: 'http://www.landingpageurl1.com',
      rowIndex: 4,
      errorCount: 0,
    },
  ], // LandingPages
  [
    {
      CampaignName: 'Campaign1',
      Name: 'Target1',
      Bid: '123',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      Name: 'Target2',
      Bid: '124',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Name: 'Target3',
      Bid: '125',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Name: 'Target4',
      Bid: '126',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'Target5',
      Bid: '127',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'Target6',
      Bid: '128',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'Target7',
      Bid: '129',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Name: 'Target8',
      Bid: '130',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Name: 'Target9',
      Bid: '131',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Name: 'Target10',
      Bid: '132',
      rowIndex: 9,
      errorCount: 0,
    },
  ], // Targets
  [
    {
      TargetName: 'Target1',
      Type: 'asinReviewRatingLessThan',
      Value: '2-5',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      TargetName: 'Target1',
      Type: 'asinCategorySameAs',
      Value: '2-6',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      TargetName: 'Target1',
      Type: 'asinCategorySameAs',
      Value: '2-7',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      TargetName: 'Target1',
      Type: 'asinReviewRatingLessThan',
      Value: '2-8',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      TargetName: 'Target1',
      Type: 'asinPriceLessThan',
      Value: '2-9',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      TargetName: 'Target2',
      Type: 'asinCategorySameAs',
      Value: '2-10',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      TargetName: 'Target2',
      Type: 'asinReviewRatingGreaterThan',
      Value: '2-11',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinCategorySameAs',
      Value: '2-12',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinCategorySameAs',
      Value: '2-13',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinCategorySameAs',
      Value: '2-14',
      rowIndex: 9,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinReviewRatingLessThan',
      Value: '2-15',
      rowIndex: 10,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinCategorySameAs',
      Value: '2-16',
      rowIndex: 11,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinPriceLessThan',
      Value: '2-17',
      rowIndex: 12,
      errorCount: 0,
    },
    {
      TargetName: 'Target4',
      Type: 'asinReviewRatingGreaterThan',
      Value: '2-18',
      rowIndex: 13,
      errorCount: 0,
    },
    {
      TargetName: 'Target5',
      Type: 'asinCategorySameAs',
      Value: '2-19',
      rowIndex: 14,
      errorCount: 0,
    },
    {
      TargetName: 'Target5',
      Type: 'asinCategorySameAs',
      Value: '2-20',
      rowIndex: 15,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinPriceLessThan',
      Value: '2-21',
      rowIndex: 16,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinReviewRatingLessThan',
      Value: '2-22',
      rowIndex: 17,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinCategorySameAs',
      Value: '2-23',
      rowIndex: 18,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinCategorySameAs',
      Value: '2-24',
      rowIndex: 19,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinPriceLessThan',
      Value: '2-25',
      rowIndex: 20,
      errorCount: 0,
    },
    {
      TargetName: 'Target7',
      Type: 'asinCategorySameAs',
      Value: '2-26',
      rowIndex: 21,
      errorCount: 0,
    },
    {
      TargetName: 'Target8',
      Type: 'asinCategorySameAs',
      Value: '2-27',
      rowIndex: 22,
      errorCount: 0,
    },
    {
      TargetName: 'Target8',
      Type: 'asinReviewRatingLessThan',
      Value: '2-28',
      rowIndex: 23,
      errorCount: 0,
    },
    {
      TargetName: 'Target9',
      Type: 'asinPriceLessThan',
      Value: '2-29',
      rowIndex: 24,
      errorCount: 0,
    },
    {
      TargetName: 'Target9',
      Type: 'asinCategorySameAs',
      Value: '2-30',
      rowIndex: 25,
      errorCount: 0,
    },
    {
      TargetName: 'Target9',
      Type: 'asinCategorySameAs',
      Value: '2-31',
      rowIndex: 26,
      errorCount: 0,
    },
    {
      TargetName: 'Target10',
      Type: 'asinCategorySameAs',
      Value: '2-32',
      rowIndex: 27,
      errorCount: 0,
    },
  ], // Expressions
  [
    {
      CampaignName: 'Campaign1',
      Name: 'NegativeTarget1',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Name: 'NegativeTarget2',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'NegativeTarget3',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Name: 'NegativeTarget4',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Name: 'NegativeTarget5',
      rowIndex: 9,
      errorCount: 0,
    },
  ], // NegativeTargets
  [
    {
      NegativeTargetName: 'NegativeTarget1',
      Type: 'asinReviewRatingLessThan',
      Value: '2-5',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'NegativeTarget2',
      Type: 'asinCategorySameAs',
      Value: '2-6',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'NegativeTarget2',
      Type: 'asinCategorySameAs',
      Value: '2-7',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'NegativeTarget2',
      Type: 'asinReviewRatingLessThan',
      Value: '2-8',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'NegativeTarget3',
      Type: 'asinPriceLessThan',
      Value: '2-9',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'NegativeTarget3',
      Type: 'asinCategorySameAs',
      Value: '2-10',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'NegativeTarget4',
      Type: 'asinReviewRatingGreaterThan',
      Value: '2-11',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'NegativeTarget4',
      Type: 'asinCategorySameAs',
      Value: '2-12',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'NegativeTarget4',
      Type: 'asinCategorySameAs',
      Value: '2-13',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'NegativeTarget5',
      Type: 'asinCategorySameAs',
      Value: '2-14',
      rowIndex: 9,
      errorCount: 0,
    },
  ], // NegativeExpressions
];
export const SBVE_WORKBOOK = [
  [
    {
      Name: 'Campaign1',
      Budget: '1111',
      BudgetType: 'lifetime',
      StartDate: '2021/08/05',
      EndDate: '2021/08/05',
      AdFormat: 'productCollection',
      State: 'enabled',
      BrandEntityId: 'id1',
      PortfolioId: '23432',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      Name: 'Campaign2',
      Budget: '2222',
      BudgetType: 'daily',
      StartDate: '2021/08/05',
      EndDate: '2021/08/05',
      AdFormat: 'productCollection',
      State: 'archived',
      BrandEntityId: 'id2',
      PortfolioId: '4243',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      Name: 'Campaign3',
      Budget: '3333',
      BudgetType: 'lifetime',
      StartDate: '2021/08/05',
      EndDate: '2021/08/05',
      AdFormat: 'productCollection',
      State: 'archived',
      BrandEntityId: 'id3',
      PortfolioId: '2345',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      Name: 'Campaign4',
      Budget: '4444',
      BudgetType: 'lifetime',
      StartDate: '2021/08/05',
      EndDate: '2021/08/05',
      AdFormat: 'video',
      State: 'paused',
      BrandEntityId: 'id4',
      PortfolioId: '564',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      Name: 'Campaign5',
      Budget: '5555',
      BudgetType: 'daily',
      StartDate: '2021/08/05',
      EndDate: '2021/08/05',
      AdFormat: 'video',
      State: 'enabled',
      BrandEntityId: 'id5',
      PortfolioId: '6878',
      rowIndex: 4,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      Asins: 'creativeasin1, creativeasin2, creativeasin3',
      VideoMediaIds:
        'creativevideomediaids1, creativevideomediaids2, landingpage3',
      Type: 'video',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Asins: 'creativeasin5, creativeasin6, creativeasin7',
      VideoMediaIds:
        'creativevideomediaids1, creativevideomediaids2, landingpage4',
      Type: 'video',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Asins: 'creativeasin8, creativeasin9, creativeasin10',
      VideoMediaIds:
        'creativevideomediaids1, creativevideomediaids2, landingpage5',
      Type: 'video',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Asins: 'creativeasin11, creativeasin12, creativeasin13',
      VideoMediaIds:
        'creativevideomediaids1, creativevideomediaids2, landingpage6',
      Type: 'video',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Asins: 'creativeasin14, creativeasin15, creativeasin16',
      VideoMediaIds:
        'creativevideomediaids1, creativevideomediaids2, landingpage7',
      Type: 'video',
      rowIndex: 4,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      Name: 'Target1',
      Bid: '123',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      Name: 'Target2',
      Bid: '124',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Name: 'Target3',
      Bid: '125',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Name: 'Target4',
      Bid: '126',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'Target5',
      Bid: '127',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'Target6',
      Bid: '128',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'Target7',
      Bid: '129',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Name: 'Target8',
      Bid: '130',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Name: 'Target9',
      Bid: '131',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Name: 'Target10',
      Bid: '132',
      rowIndex: 9,
      errorCount: 0,
    },
  ],
  [
    {
      TargetName: 'Target1',
      Type: 'asinReviewRatingLessThan',
      Value: '2-5',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      TargetName: 'Target1',
      Type: 'asinCategorySameAs',
      Value: '2-6',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      TargetName: 'Target1',
      Type: 'asinCategorySameAs',
      Value: '2-7',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      TargetName: 'Target1',
      Type: 'asinReviewRatingLessThan',
      Value: '2-8',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      TargetName: 'Target1',
      Type: 'asinPriceLessThan',
      Value: '2-9',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      TargetName: 'Target2',
      Type: 'asinCategorySameAs',
      Value: '2-10',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      TargetName: 'Target2',
      Type: 'asinReviewRatingGreaterThan',
      Value: '2-11',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinCategorySameAs',
      Value: '2-12',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinCategorySameAs',
      Value: '2-13',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinCategorySameAs',
      Value: '2-14',
      rowIndex: 9,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinReviewRatingLessThan',
      Value: '2-15',
      rowIndex: 10,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinCategorySameAs',
      Value: '2-16',
      rowIndex: 11,
      errorCount: 0,
    },
    {
      TargetName: 'Target3',
      Type: 'asinPriceLessThan',
      Value: '2-17',
      rowIndex: 12,
      errorCount: 0,
    },
    {
      TargetName: 'Target4',
      Type: 'asinReviewRatingGreaterThan',
      Value: '2-18',
      rowIndex: 13,
      errorCount: 0,
    },
    {
      TargetName: 'Target5',
      Type: 'asinCategorySameAs',
      Value: '2-19',
      rowIndex: 14,
      errorCount: 0,
    },
    {
      TargetName: 'Target5',
      Type: 'asinCategorySameAs',
      Value: '2-20',
      rowIndex: 15,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinPriceLessThan',
      Value: '2-21',
      rowIndex: 16,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinReviewRatingLessThan',
      Value: '2-22',
      rowIndex: 17,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinCategorySameAs',
      Value: '2-23',
      rowIndex: 18,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinCategorySameAs',
      Value: '2-24',
      rowIndex: 19,
      errorCount: 0,
    },
    {
      TargetName: 'Target6',
      Type: 'asinPriceLessThan',
      Value: '2-25',
      rowIndex: 20,
      errorCount: 0,
    },
    {
      TargetName: 'Target7',
      Type: 'asinCategorySameAs',
      Value: '2-26',
      rowIndex: 21,
      errorCount: 0,
    },
    {
      TargetName: 'Target8',
      Type: 'asinCategorySameAs',
      Value: '2-27',
      rowIndex: 22,
      errorCount: 0,
    },
    {
      TargetName: 'Target8',
      Type: 'asinReviewRatingLessThan',
      Value: '2-28',
      rowIndex: 23,
      errorCount: 0,
    },
    {
      TargetName: 'Target9',
      Type: 'asinPriceLessThan',
      Value: '2-29',
      rowIndex: 24,
      errorCount: 0,
    },
    {
      TargetName: 'Target9',
      Type: 'asinCategorySameAs',
      Value: '2-30',
      rowIndex: 25,
      errorCount: 0,
    },
    {
      TargetName: 'Target9',
      Type: 'asinCategorySameAs',
      Value: '2-31',
      rowIndex: 26,
      errorCount: 0,
    },
    {
      TargetName: 'Target10',
      Type: 'asinCategorySameAs',
      Value: '2-32',
      rowIndex: 27,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      Name: 'TargetName1',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Name: 'TargetName2',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'TargetName3',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Name: 'TargetName4',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Name: 'TargetName5',
      rowIndex: 4,
      errorCount: 0,
    },
  ],
  [
    {
      NegativeTargetName: 'TargetName1',
      Type: 'asinReviewRatingLessThan',
      Value: '2-5',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'TargetName2',
      Type: 'asinCategorySameAs',
      Value: '2-6',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'TargetName2',
      Type: 'asinCategorySameAs',
      Value: '2-7',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'TargetName2',
      Type: 'asinReviewRatingLessThan',
      Value: '2-8',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'TargetName3',
      Type: 'asinPriceLessThan',
      Value: '2-9',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'TargetName3',
      Type: 'asinCategorySameAs',
      Value: '2-10',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'TargetName4',
      Type: 'asinReviewRatingGreaterThan',
      Value: '2-11',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'TargetName4',
      Type: 'asinCategorySameAs',
      Value: '2-12',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'TargetName4',
      Type: 'asinCategorySameAs',
      Value: '2-13',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      NegativeTargetName: 'TargetName5',
      Type: 'asinCategorySameAs',
      Value: '2-14',
      rowIndex: 9,
      errorCount: 0,
    },
  ],
];
export const SD_WORKBOOK = [
  [
    {
      Name: 'Campaign1',
      Budget: '3.01',
      BudgetType: 'daily',
      StartDate: '2021/08/05',
      EndDate: '2021/08/05',
      CostType: 'cpc',
      State: 'enabled',
      PortfolioId: '1234',
      Tactic: 'T00030',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      Name: 'Campaign2',
      Budget: '3.02',
      BudgetType: 'daily',
      StartDate: '2021/08/05',
      EndDate: '2021/08/05',
      CostType: 'cpc',
      State: 'archived',
      PortfolioId: '1235',
      Tactic: 'T00020',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      Name: 'Campaign3',
      Budget: '3.03',
      BudgetType: 'daily',
      StartDate: '2021/08/05',
      EndDate: '2021/08/05',
      CostType: 'vcpm',
      State: 'enabled',
      PortfolioId: '1236',
      Tactic: 'T00020',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      Name: 'Campaign4',
      Budget: '3.04',
      BudgetType: 'daily',
      StartDate: '2021/08/05',
      EndDate: '2021/08/05',
      CostType: 'cpc',
      State: 'archived',
      PortfolioId: '1237',
      Tactic: 'T00030',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      Name: 'Campaign5',
      Budget: '3.05',
      BudgetType: 'daily',
      StartDate: '2021/08/05',
      EndDate: '2021/08/05',
      CostType: 'vcpm',
      State: 'enabled',
      PortfolioId: '1238',
      Tactic: 'T00020',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      Name: 'Campaign6',
      Budget: '3.06',
      BudgetType: 'daily',
      StartDate: '2021/08/05',
      EndDate: '2021/08/05',
      CostType: 'cpc',
      State: 'paused',
      PortfolioId: '1239',
      Tactic: 'T00030',
      rowIndex: 5,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      Name: 'AdGroup1',
      DefaultBid: '1.23',
      BidOptimization: 'conversions',
      State: 'enabled',
      Tactic: 'T00020',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Name: 'AdGroup2',
      DefaultBid: '1.24',
      BidOptimization: 'clicks',
      State: 'paused',
      Tactic: 'T00030',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Name: 'AdGroup3',
      DefaultBid: '1.25',
      BidOptimization: 'clicks',
      State: 'enabled',
      Tactic: 'T00020',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Name: 'AdGroup4',
      DefaultBid: '1.26',
      BidOptimization: 'clicks',
      State: 'paused',
      Tactic: 'T00020',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'AdGroup5',
      DefaultBid: '1.27',
      BidOptimization: 'conversions',
      State: 'enabled',
      Tactic: 'T00020',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'AdGroup6',
      DefaultBid: '1.28',
      BidOptimization: 'clicks',
      State: 'paused',
      Tactic: 'T00030',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'AdGroup7',
      DefaultBid: '1.29',
      BidOptimization: 'conversions',
      State: 'enabled',
      Tactic: 'T00030',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Name: 'AdGroup8',
      DefaultBid: '1.3',
      BidOptimization: 'reach',
      State: 'enabled',
      Tactic: 'T00030',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Name: 'AdGroup9',
      DefaultBid: '1.31',
      BidOptimization: 'conversions',
      State: 'archived',
      Tactic: 'T00030',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign6',
      Name: 'AdGroup10',
      DefaultBid: '1.32',
      BidOptimization: 'conversions',
      State: 'archived',
      Tactic: 'T00030',
      rowIndex: 9,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      State: 'enabled',
      AdGroupName: '123334',
      Asin: 'asin1',
      Sku: 'sku1',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      State: 'paused',
      AdGroupName: '123335',
      Asin: 'asin2',
      Sku: 'sku2',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      State: 'enabled',
      AdGroupName: '123336',
      Asin: 'asin3',
      Sku: 'sku3',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      State: 'paused',
      AdGroupName: '123337',
      Asin: 'asin4',
      Sku: 'sku4',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      State: 'enabled',
      AdGroupName: '123338',
      Asin: 'asin5',
      Sku: 'sku5',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      State: 'archived',
      AdGroupName: '123339',
      Asin: 'asin6',
      Sku: 'sku6',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      State: 'archived',
      AdGroupName: '123340',
      Asin: 'asin7',
      Sku: 'sku7',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      State: 'enabled',
      AdGroupName: '123341',
      Asin: 'asin8',
      Sku: 'sku8',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      State: 'archived',
      AdGroupName: '123342',
      Asin: 'asin9',
      Sku: 'sku9',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      State: 'enabled',
      AdGroupName: '123343',
      Asin: 'asin10',
      Sku: 'sku10',
      rowIndex: 9,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign6',
      State: 'enabled',
      AdGroupName: '123344',
      Asin: 'asin11',
      Sku: 'sku11',
      rowIndex: 10,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign6',
      State: 'archived',
      AdGroupName: '123345',
      Asin: 'asin12',
      Sku: 'sku12',
      rowIndex: 11,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      Name: 'Targeting1',
      State: 'enabled',
      Bid: '1.5',
      AdGroupName: '2345',
      ExpressionType: 'manual',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      Name: 'Targeting2',
      State: 'enabled',
      Bid: '1.6',
      AdGroupName: '2346',
      ExpressionType: 'auto',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Name: 'Targeting3',
      State: 'enabled',
      Bid: '1.7',
      AdGroupName: '2347',
      ExpressionType: 'manual',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'Targeting4',
      State: 'paused',
      Bid: '1.8',
      AdGroupName: '2348',
      ExpressionType: 'auto',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Name: 'Targeting5',
      State: 'enabled',
      Bid: '1.9',
      AdGroupName: '2349',
      ExpressionType: 'manual',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Name: 'Targeting6',
      State: 'archived',
      Bid: '2',
      AdGroupName: '2350',
      ExpressionType: 'manual',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Name: 'Targeting7',
      State: 'enabled',
      Bid: '2.1',
      AdGroupName: '2351',
      ExpressionType: 'manual',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Name: 'Targeting8',
      State: 'archived',
      Bid: '2.2',
      AdGroupName: '2352',
      ExpressionType: 'manual',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign6',
      Name: 'Targeting9',
      State: 'enabled',
      Bid: '2.3',
      AdGroupName: '2353',
      ExpressionType: 'auto',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign6',
      Name: 'Targeting10',
      State: 'archived',
      Bid: '2.4',
      AdGroupName: '2354',
      ExpressionType: 'auto',
      rowIndex: 9,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign6',
      Name: 'Targeting11',
      State: 'archived',
      Bid: '2.5',
      AdGroupName: '2355',
      ExpressionType: 'auto',
      rowIndex: 10,
      errorCount: 0,
    },
  ],
  [
    {
      TargetingName: 'Targeting1',
      Name: '',
      Type: 'asinSameAs',
      Value: 'B01234567',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting1',
      Name: '',
      Type: 'asinCategorySameAs',
      Value: 'B01234568',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting1',
      Name: '',
      Type: 'asinSameAs',
      Value: 'B01234569',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting2',
      Name: '',
      Type: 'asinCategorySameAs',
      Value: 'B01234570',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting3',
      Name: '',
      Type: 'asinCategorySameAs',
      Value: 'B01234571',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting3',
      Name: '',
      Type: 'asinSameAs',
      Value: 'B01234572',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting4',
      Name: '',
      Type: 'asinCategorySameAs',
      Value: 'B01234573',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting5',
      Name: '',
      Type: 'asinBrandSameAs',
      Value: 'B01234574',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting5',
      Name: '',
      Type: 'asinCategorySameAs',
      Value: 'B01234575',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting5',
      Name: 'Expression1',
      Type: 'views',
      Value: '',
      rowIndex: 9,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting5',
      Name: '',
      Type: 'asinBrandSameAs',
      Value: 'B01234577',
      rowIndex: 10,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting6',
      Name: 'Expression2',
      Type: 'audience',
      Value: '',
      rowIndex: 11,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting7',
      Name: '',
      Type: 'asinBrandSameAs',
      Value: 'B01234579',
      rowIndex: 12,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting8',
      Name: 'Expression3',
      Type: 'audience',
      Value: '',
      rowIndex: 13,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting9',
      Name: '',
      Type: 'asinAgeRangeSameAs',
      Value: 'B01234581',
      rowIndex: 14,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting9',
      Name: '',
      Type: 'asinAgeRangeSameAs',
      Value: 'B01234582',
      rowIndex: 15,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting10',
      Name: '',
      Type: 'asinAgeRangeSameAs',
      Value: 'B01234583',
      rowIndex: 16,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting11',
      Name: 'Expression4',
      Type: 'purchases',
      Value: '',
      rowIndex: 17,
      errorCount: 0,
    },
    {
      TargetingName: 'Targeting11',
      Name: 'Expression5',
      Type: 'purchases',
      Value: '',
      rowIndex: 18,
      errorCount: 0,
    },
  ],
  [
    {
      ExpressionName: 'Expression1',
      Type: 'asinBrandSameAs',
      Value: 'N012345678',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      ExpressionName: 'Expression1',
      Type: 'asinBrandSameAs',
      Value: 'N012345679',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      ExpressionName: 'Expression2',
      Type: 'asinIsPrimeShippingEligible',
      Value: 'N012345680',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      ExpressionName: 'Expression2',
      Type: 'asinBrandSameAs',
      Value: 'N012345681',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      ExpressionName: 'Expression2',
      Type: 'relatedProduct',
      Value: 'N012345682',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      ExpressionName: 'Expression3',
      Type: 'asinIsPrimeShippingEligible',
      Value: 'N012345683',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      ExpressionName: 'Expression4',
      Type: 'relatedProduct',
      Value: 'N012345684',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      ExpressionName: 'Expression4',
      Type: 'relatedProduct',
      Value: 'N012345685',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      ExpressionName: 'Expression5',
      Type: 'asinIsPrimeShippingEligible',
      Value: 'N012345686',
      rowIndex: 8,
      errorCount: 0,
    },
  ],
  [
    {
      CampaignName: 'Campaign1',
      Name: 'NegativeTargeting1',
      State: 'paused',
      AdGroupName: '6789',
      ExpressionType: 'auto',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign1',
      Name: 'NegativeTargeting2',
      State: 'enabled',
      AdGroupName: '6790',
      ExpressionType: 'manual',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign2',
      Name: 'NegativeTargeting3',
      State: 'paused',
      AdGroupName: '6791',
      ExpressionType: 'auto',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign3',
      Name: 'NegativeTargeting4',
      State: 'paused',
      AdGroupName: '6792',
      ExpressionType: 'manual',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Name: 'NegativeTargeting5',
      State: 'enabled',
      AdGroupName: '6793',
      ExpressionType: 'auto',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Name: 'NegativeTargeting6',
      State: 'paused',
      AdGroupName: '6794',
      ExpressionType: 'auto',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign4',
      Name: 'NegativeTargeting7',
      State: 'paused',
      AdGroupName: '6795',
      ExpressionType: 'manual',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Name: 'NegativeTargeting8',
      State: 'enabled',
      AdGroupName: '6796',
      ExpressionType: 'auto',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Name: 'NegativeTargeting9',
      State: 'paused',
      AdGroupName: '6797',
      ExpressionType: 'auto',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Name: 'NegativeTargeting10',
      State: 'enabled',
      AdGroupName: '6798',
      ExpressionType: 'auto',
      rowIndex: 9,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign5',
      Name: 'NegativeTargeting11',
      State: 'enabled',
      AdGroupName: '6799',
      ExpressionType: 'auto',
      rowIndex: 10,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign6',
      Name: 'NegativeTargeting12',
      State: 'enabled',
      AdGroupName: '6800',
      ExpressionType: 'manual',
      rowIndex: 11,
      errorCount: 0,
    },
    {
      CampaignName: 'Campaign6',
      Name: 'NegativeTargeting13',
      State: 'archived',
      AdGroupName: '6801',
      ExpressionType: 'manual',
      rowIndex: 12,
      errorCount: 0,
    },
  ],
  [
    {
      NegativeTargetingName: 'NegativeTargeting1',
      Type: 'asinSameAs',
      Value: 'B0123456789',
      rowIndex: 0,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting1',
      Type: 'asinBrandSameAs',
      Value: 'B0123456790',
      rowIndex: 1,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting1',
      Type: 'asinBrandSameAs',
      Value: 'B0123456791',
      rowIndex: 2,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting2',
      Type: 'asinBrandSameAs',
      Value: 'B0123456792',
      rowIndex: 3,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting3',
      Type: 'asinSameAs',
      Value: 'B0123456793',
      rowIndex: 4,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting3',
      Type: 'asinBrandSameAs',
      Value: 'B0123456794',
      rowIndex: 5,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting4',
      Type: 'asinSameAs',
      Value: 'B0123456795',
      rowIndex: 6,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting4',
      Type: 'asinBrandSameAs',
      Value: 'B0123456796',
      rowIndex: 7,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting5',
      Type: 'asinSameAs',
      Value: 'B0123456797',
      rowIndex: 8,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting6',
      Type: 'asinBrandSameAs',
      Value: 'B0123456798',
      rowIndex: 9,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting7',
      Type: 'asinBrandSameAs',
      Value: 'B0123456799',
      rowIndex: 10,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting7',
      Type: 'asinSameAs',
      Value: 'B0123456800',
      rowIndex: 11,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting7',
      Type: 'asinBrandSameAs',
      Value: 'B0123456801',
      rowIndex: 12,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting7',
      Type: 'asinSameAs',
      Value: 'B0123456802',
      rowIndex: 13,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting8',
      Type: 'asinBrandSameAs',
      Value: 'B0123456803',
      rowIndex: 14,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting9',
      Type: 'asinSameAs',
      Value: 'B0123456804',
      rowIndex: 15,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting9',
      Type: 'asinBrandSameAs',
      Value: 'B0123456805',
      rowIndex: 16,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting9',
      Type: 'asinBrandSameAs',
      Value: 'B0123456806',
      rowIndex: 17,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting10',
      Type: 'asinSameAs',
      Value: 'B0123456807',
      rowIndex: 18,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting11',
      Type: 'asinSameAs',
      Value: 'B0123456808',
      rowIndex: 19,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting12',
      Type: 'asinSameAs',
      Value: 'B0123456809',
      rowIndex: 20,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting12',
      Type: 'asinBrandSameAs',
      Value: 'B0123456810',
      rowIndex: 21,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting13',
      Type: 'asinBrandSameAs',
      Value: 'B0123456811',
      rowIndex: 22,
      errorCount: 0,
    },
    {
      NegativeTargetingName: 'NegativeTargeting13',
      Type: 'asinBrandSameAs',
      Value: 'B0123456812',
      rowIndex: 23,
      errorCount: 0,
    },
  ],
];
